sudo: false
language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
Script:
  - gofmt -w api.go
  - go test -v api.go
  - go build api.go
