sudo: false
language: go
go:
  - 1.8.x
  - 1.9.x
  - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - go fmt -w ./...
  - go test -v -race ./...                   # Run all the tests with the race detector enabled
  - make integrationtest
  - make